#!/bin/bash

# PhishGuard AI - Quick Reference Guide
# All commands and common operations

echo "PhishGuard AI - Quick Reference"
echo "================================"
echo ""
echo "1. LOCAL DEVELOPMENT"
echo "   ./quickstart.sh          # Linux/Mac quick start"
echo "   ./quickstart.bat         # Windows quick start"
echo "   python backend/app.py    # Run backend only"
echo ""
echo "2. DOCKER"
echo "   docker-compose up --build        # Start all services"
echo "   docker-compose down              # Stop services"
echo "   docker-compose logs -f           # View logs"
echo "   docker-compose restart           # Restart services"
echo ""
echo "3. PYTHON SETUP"
echo "   python -m venv venv              # Create virtual environment"
echo "   source venv/bin/activate         # Activate (Linux/Mac)"
echo "   venv\\Scripts\\activate.bat       # Activate (Windows)"
echo "   pip install -r backend/requirements.txt  # Install deps"
echo ""
echo "4. TESTING"
echo "   pytest tests/ -v                 # Run all tests"
echo "   pytest tests/ -v --cov=backend   # With coverage"
echo "   pytest tests/test_api.py         # Run specific test"
echo ""
echo "5. DEVELOPMENT"
echo "   python backend/app.py            # Dev server (with auto-reload)"
echo "   uvicorn backend.app:app --reload # Alternative dev server"
echo ""
echo "6. PRODUCTION"
echo "   gunicorn --bind 0.0.0.0:8000 --workers 4 backend.app:app"
echo ""
echo "7. DEPLOYMENT"
echo "   # Heroku"
echo "   heroku create phishguard-ai"
echo "   git push heroku main"
echo ""
echo "   # Docker Hub"
echo "   docker build -t phishguard-ai:latest ."
echo "   docker run -p 8000:8000 phishguard-ai:latest"
echo ""
echo "8. ENVIRONMENT VARIABLES"
echo "   ENVIRONMENT=production           # Set to production"
echo "   API_WORKERS=4                   # Number of workers"
echo "   LOG_LEVEL=INFO                  # Logging level"
echo ""
echo "9. USEFUL URLS (when running locally)"
echo "   http://localhost:8000           # Main app"
echo "   http://localhost:8000/docs      # API documentation"
echo "   http://localhost:8000/redoc     # ReDoc documentation"
echo "   http://localhost:8000/health    # Health check"
echo "   http://localhost:8000/api/analyze  # API endpoint"
echo ""
echo "10. API CALLS"
echo "    # Analyze single URL"
echo "    curl -X POST http://localhost:8000/api/analyze \\"
echo '      -H "Content-Type: application/json" \\'
echo '      -d "{\"url\": \"https://example.com\"}"'
echo ""
echo "11. FILES TO EDIT"
echo "    backend/app.py              # Main API application"
echo "    frontend/index.html         # Web interface"
echo "    ml_model/detector.py        # ML model logic"
echo "    backend/config.py           # Configuration"
echo ""
echo "12. KEY DOCUMENTATION"
echo "    README.md                   # Getting started"
echo "    ARCHITECTURE.md             # Technical design"
echo "    DEPLOYMENT_GUIDE.md         # Deployment instructions"
echo "    API_DOCUMENTATION.md        # API reference"
echo ""
echo "13. GIT COMMANDS"
echo "    git add ."
echo "    git commit -m 'Your message'"
echo "    git push origin main"
echo ""
echo "14. TROUBLESHOOTING"
echo "    # Port already in use"
echo "    # Windows: netstat -ano | findstr :8000"
echo "    # Linux/Mac: lsof -i :8000"
echo ""
echo "    # Clear Docker containers"
echo "    docker-compose down -v"
echo "    docker system prune"
echo ""
echo "    # Rebuild dependencies"
echo "    pip install --upgrade -r backend/requirements.txt"
echo ""
echo "15. MONITORING"
echo "    tail -f logs/production.log     # View logs"
echo "    docker stats                    # Container stats"
echo "    htop                           # System monitor (Linux/Mac)"
echo ""
